import turtle
import math
from random import *
hill = turtle.Turtle()
angle=math.radians(int(input("What degree angle?")))
magnitude = int(input("What is the hypotenuse of the hill?"))
massBox=int(input("What is the mass of the box?"))
weightBox=int(9.8*massBox)
hill.forward(magnitude*math.cos(angle))
hill.left(90)
hill.forward(magnitude*math.sin(angle)) 
angle=math.degrees(angle)
hill.left(90+angle)
hill.forward(magnitude)
hill.hideturtle()

box = turtle.Turtle()
box.left(angle)
box.forward(magnitude/2)
box.left(90)
box.forward(10)
box.right(90)
box.forward(15)
box.right(90)
box.forward(10)
box.hideturtle()

weightVector=turtle.Turtle()
weightVector.color(0,100,200)
weightVector.left(angle)
weightVector.forward((magnitude/2)+7)
weightVector.right(angle+90)
weightVector.forward(weightBox)
weightVector.write(weightBox)

for i in range(0,10):
	x=randint(0,200)
	y=randint(0,200)
	z=randint(0,200)
	normalVector=turtle.Turtle()
	normalVector.color(x,y,z)
	normalVector.penup()
	normalVector.left(angle)
	normalVector.forward((magnitude/2)+7)
	normalVector.pendown()
	normalVector.left(90)
	normalVector.forward(weightBox*(math.cos(math.radians(angle))))
	normalVector.write(weightBox*(math.cos(math.radians(angle))))

turtle.hideturtle()
